<a href="https://colab.research.google.com/github/Lmootha/LetsUpgrade-Data-Science-101/blob/main/Day3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [ ]:
# to create an array from 2 to 50 with step size 3
import numpy as np
l = [i for i in range(2,51,3)]
print(np.array(l))
print(type(np.array(l)))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


Question 2


In [ ]:
# To accept two list from user as input and print nparrays and sorted np arrays
import numpy as np
inp1 = input('Enter the list of 5 elements in List 1 separated by space')
inp2 = input('Enter the list of 5 elements in List 2 separated by space')

list1 = inp1.split()
list2 = inp2.split()

array1 = np.array(list1)
array2 = np.array(list2)

array3 = np.concatenate((array1,array2))
print(array3)

print(np.sort(array3))


Enter the list of 5 numbers in List 1 separated by space1 2 3 4 5
Enter the list of 5 numbers in List 2 separated by space0 0 0 0 08 7
[1 2 3 4 5 0 0 0 0 8 7]
[0 0 0 0 1 2 3 4 5 7 8]


Question 3

In [ ]:
# to find dimension and size of ndarray
import numpy as np
l = [i for i in range(1,10)]
arr = np.array(l)
print(np.ndim(arr))
print(np.size(arr))


1
9


Question 4

In [2]:
# to convert a 1D array into a 2D array using reshape
import numpy as np
l = [i for i in range(1,10)]
arr = np.array(l)
size = np.size(arr)
np.reshape(arr, (-1, size))


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
# to convert a 1D array into a 2D array using expand_dms
import numpy as np
l = [i for i in range(1,10)]
arr = np.array(l)
arrnew = np.expand_dims(arr, axis=1)
arrnew


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
# to convert a 1D array into a 2D array using newaxis
import numpy as np
l = [i for i in range(1,10)]
arr = np.array(l)
arrnew = arr [np.newaxis]
arrnew

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Question 5

In [8]:
# Stacking two square matrices vertically and horizontally
import numpy as np
inp1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
inp2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] ) 

print(np.vstack((inp1,inp2)))
print(np.hstack((inp1,inp2)))

[[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]
[[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


Question 6

In [10]:
# To get unique item and count of unique item
import numpy as np

a = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))


{0: 7, 1: 4, 2: 1, 3: 2, 4: 1}